# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!

target 'happyBycle' do

#下拉刷新
    pod 'MJRefresh', '~> 3.1.12'
#json解析
    pod 'MJExtension', '~> 3.0.13'

  #侧滑手势
  pod 'FDFullscreenPopGesture', '~> 1.1'

 pod 'Masonry', '~> 1.0.2'
pod 'SDWebImage', '~> 4.0.0'
#网络访问与缓存
pod 'AFNetworking', '~> 3.1.0'
pod 'YYCache', '~> 1.0.4'
pod 'Reachability', '~> 3.2'
end
